# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1df069658529e7a37488f3ce1bbdebfc"
name = "indexbeam-ai"
application_url = "https://indexbeam-ai.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "products/delete" ]
  uri = "/webhooks/products"

  [[webhooks.subscriptions]]
  topics = [ "collections/create", "collections/update" ]
  uri = "/webhooks/collections"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions-update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://indexbeam-ai.fly.dev/api/auth" ]

[app_proxy]
url = "https://indexbeam-ai.fly.dev/api/proxy"
subpath = "indexnow"
prefix = "apps"
